[Feat] 여행스페이스 내 타이틀 변경기능 요구사항 변경 적용
Strong-Potato/TripVote-BE pull request #149
Opened 2024-01-21 12:13 UTC by NoJaeHyuk

## 변경사항

- 여행스페이스 도시 선택 구현 
     -  도시의 데이터는 Enum 구현 
     -  도시리스트 호출 API 구현
     -  기본 타이틀 명 받는 형식에서 선택 도시항목 받도록 구현
- 여행스페이스 생성 시 타이틀 명 적용되게 구현
     -  닉네임 + "의 여행"
     
### Issue Link - #135

2024-01-21 15:33 UTC, laigasus approved these changes
수고하셨습니다 🙇

코멘트 남겼습니다!

마지막까지 ㅎㅇㅌ 입니다 💪

2024-01-21 15:33 UTC, laigasus commented on app/src/main/java/fc/be/app/domain/space/dto/response/CitiesResponse.java
> +    }
public 으로 해야만 했을 까요?

2024-01-21 15:33 UTC, laigasus commented on app/src/main/java/fc/be/app/domain/space/controller/SpaceController.java
> +    }
정적 자원을 우리 api 서버를 통해서
제공해줄 필요가 있는지 고민해볼 것 같아요.

s3 등의 특정 저장소에서 json으로 만들어두면 함께 관리하기도 쉬울 것 같아요.
번거로우면 파일 폼 만들어두고 공유할 수 도 있는 것이고요.

우리 백엔드에서는 앱 실행시 최초 1회 로딩하여 Map으로 관리하고
프론트에서는 정적 리소스에 접근하여 이용하면 되니까용

2024-01-21 15:33 UTC, laigasus commented on app/src/main/java/fc/be/app/domain/space/vo/KoreanCity.java
openapi 모듈 내에 대한민국 행정구역을 조회할 수 있는(한국관광공사 데이터 기준)
`AreaFinder`  클래스가 있습니다.

제 영역에서는 결국 사용을 안한 지라.
따로 이용하셔도 됩니다.

프론트분들께 사전에 `areas.json` 을 공유드린 적이 있으니 참고하시면 좋을 것 같아요.

2024-01-21 15:33 UTC, laigasus commented on app/src/main/java/fc/be/app/domain/space/vo/KoreanCity.java
이또한 정적 리소스를 담고 있으니, 
코드 내애 작성하는 것을 권하고 싶진 않네요

2024-01-21 15:33 UTC, laigasus commented on app/src/main/java/fc/be/app/global/util/DelimiterConverter.java
만드신 컨버터가 `ListImagesConverter` 와 동일한 코드를 가지고 있습니다.

도메인 한정 필수 사용해야 되는 클래스라 util 로 간주하기 힘들 것 같아요.

util 은 뭐랄까. 있으면 쓰는 거고, 없으면 말고. 딱 nice to have 라고 생각합니다.


저라면 클래스 이름을 바꿔서 하나로 쓴 다음에, 
`app: global.entity` 패키지에 둘 것 같아요

2024-01-21 15:35 UTC, laigasus commented
@NoJaeHyuk 리팩터링때 SpaceService와 SpaceTokenService 사용 경계를 명확히 구분할 수 있을 것 같아요!
까먹을까봐 이렇게 글 남깁니다! ㅋㅋ

2024-01-21 16:15 UTC, Nine-JH approved these changes
고생하셨습니다! 남은날까지 화이팅!

2024-01-21 16:15 UTC, Nine-JH commented on app/src/main/java/fc/be/app/domain/space/vo/KoreanCity.java
이런 정보는 참 애매하죠 ㅋㅋ 저도 @laigasus 님과 동일하게 코드 내부적으로 관리될 필요는 없다고 생각합니다.
내부 정책으로 얼마든지 바뀔 수 있는 데이터이므로 외부에서 컨트롤 가능하게끔 빼는것도 어떨까 싶네요 😄

2024-01-21 16:15 UTC, Nine-JH commented on app/src/main/java/fc/be/app/global/util/DelimiterConverter.java
생각해보니 이런 비슷한 converter을 @laigasus  님께서 `openApi` 쪽을 구현하실 때 만드신 적이 있지 않나요? 같이 써도 좋을 것 같아요

2024-01-21 16:15 UTC, Nine-JH commented on app/src/main/java/fc/be/app/domain/space/entity/Space.java
> +    }
음 이제 도시의 목록들이 제목이 되어버려서 `title`이 필요 없을 줄 알았는데 계속 쓰시는군요? 🧐

2024-01-21 16:42 UTC, happymink approved these changes
고생하셨습니다!

2024-01-21 21:06 UTC, Dr-KoKo commented on app/src/main/java/fc/be/app/domain/space/dto/response/CitiesResponse.java
> +    }
getter가 필요하셔서 public으로 쓰신 것 같네요

2024-01-21 21:13 UTC, Dr-KoKo approved these changes
수고하셨습니다.

2024-01-21 23:00 UTC, Dr-KoKo requested changes
![image](https://github.com/Strong-Potato/TripVote-BE/assets/97681286/9e045157-ea32-4036-b3fe-3e216b0e966e)
https://x-8cw6772.slack.com/archives/C068Q4JFZJ8/p1705626002051389
오늘 PM분들이 말씀하실 예정인듯 한데, 고정타이틀이 아니라 
1. space에 참여 중인 유저
2. space가 방문할 지역

정보를 카드에 보여주는 방식으로 정해질 듯 합니다.
결정사항 들어보고 변경사항 생기면 수정 후 머지하는 것이 좋겠네요.

2024-01-21 23:55 UTC, NoJaeHyuk commented on app/src/main/java/fc/be/app/domain/space/entity/Space.java
> +    }
아직 타이틀 편집에 대한 처리가 완전히 정해진 것이 아니라 일단 그래도 두었습니다.

2024-01-22 02:25 UTC, NoJaeHyuk commented on app/src/main/java/fc/be/app/domain/space/vo/KoreanCity.java
src
|-- main
    |-- resources
           |-- city.json
           
이런식으로 두고 API를 따로 만들지 않고 http://localhost:8080/city.json 이런 방식으로 호출하는 것인가요?

2024-01-22 02:48 UTC, Dr-KoKo commented
> ![image](https://private-user-images.githubusercontent.com/97681286/298420995-9e045157-ea32-4036-b3fe-3e216b0e966e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTE5ODIsIm5iZiI6MTcwNTg5MTY4MiwicGF0aCI6Ii85NzY4MTI4Ni8yOTg0MjA5OTUtOWUwNDUxNTctZWEzMi00MDM2LWIzZmUtM2UyMTZiMGU5NjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAyNDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MmNkMzMyYWI2MmE5NWY3NjcxYTBjMGJmZTgyYTU1NTQzMjZlOGJjY2FlM2M5N2QxZTVhYTk3YTMzMzc5MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eZxeES3A8ynFsIb9FyH7iZvlVhkL5LDLUgKdOC01GxQ) https://x-8cw6772.slack.com/archives/C068Q4JFZJ8/p1705626002051389 오늘 PM분들이 말씀하실 예정인듯 한데, 고정타이틀이 아니라
> 
> 1. space에 참여 중인 유저
> 2. space가 방문할 지역
> 
> 정보를 카드에 보여주는 방식으로 정해질 듯 합니다. 결정사항 들어보고 변경사항 생기면 수정 후 머지하는 것이 좋겠네요.

#160 에서 처리하도록 하겠습니다.

2024-01-22 02:49 UTC, Dr-KoKo approved these changes

2024-01-22 02:49 UTC, merged